### ISSUE TITLE
Adding apps for running terminal commands does not work

### ISSUE THREAD

**Issue by TheDeafenGuy** [lutin11/launcher-modular#1]
I tried adding an app for running a terminal command, but it did not work. It was a command to start Tailscale, but when I click the app, Tailscale does not start. I tried it with and without sudo. Also, how exactly are you getting commands working here? There have been issues in the past with other apps/scripts where commands would not work from such things.

**Comment by lutin11** [comment]
> I tried adding an app for running a terminal command, but it did not work. It was a command to start Tailscale, but when I click the app, Tailscale does not start. I tried it with and without sudo. Also, how exactly are you getting commands working here? There have been issues in the past with other apps/scripts where commands would not work from such things.

Thanks for replying,
could you try one of this depending on your architecture ?:
arm64: https://github.com/lutin11/launcher-modular/actions/runs/11040936806/artifacts/1979144461
amd64: https://github.com/lutin11/launcher-modular/actions/runs/11040936806/artifacts/1979144457

**Comment by lutin11** [comment]
Add long press to application to be able to remove it
arm64: https://github.com/lutin11/launcher-modular/actions/runs/11042717863/artifacts/1979681142
amd64: https://github.com/lutin11/launcher-modular/actions/runs/11042717863/artifacts/1979681139

**Comment by TheDeafenGuy** [comment]
Commands seem to be working now, thanks!
